plugins:
  - rubocop-internal_affairs
  - rubocop-rubyfmt
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/rubocop-rubyfmt.rb

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
